### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by StoicGilgamesh** [uber-research/UPSNet#106]
First of all thanks for this great research and the repository! Very helpful.

I have followed the instructions but when I try to train or test using pre-trained weights I get the following error. Could you please help?

upsnet/../upsnet/config/config.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
Traceback (most recent call last):
  File "upsnet/upsnet_end2end_test.py", line 44, in <module>
    from upsnet.models import *
  File "upsnet/../upsnet/models/__init__.py", line 1, in <module>
    from .resnet_upsnet import resnet_50_upsnet, resnet_101_upsnet
  File "upsnet/../upsnet/models/resnet_upsnet.py", line 27, in <module>
    from upsnet.operators.modules.pyramid_proposal import PyramidProposal
  File "upsnet/../upsnet/operators/modules/pyramid_proposal.py", line 18, in <module>
    from ..functions.pyramid_proposal import PyramidProposalFunction
  File "upsnet/../upsnet/operators/functions/pyramid_proposal.py", line 18, in <module>
    from upsnet.nms.nms import py_nms_wrapper, cpu_nms_wrapper, gpu_nms_wrapper
  File "upsnet/../upsnet/nms/nms.py", line 24, in <module>
    from .gpu_nms import gpu_nms

Is it because UPSNet specifically wants cuda 10? I have cuda 9.0 installed.

**Comment by youkibebop** [comment]
What was your solution to this problem?
