### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer    AND  ValueError: Expected input batch_size (423) to match target batch_size (465).

### ISSUE THREAD

**Issue by Xiaolongbetter** [uber-research/UPSNet#13]
When I  training the model on COCO dataset,  it can run normally at the beginning, and the loss is also decrease. But the following problems will occur in the middle：

Traceback (most recent call last):
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/connection.py", line 494, in Client
    deliver_challenge(c, authkey)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/connection.py", line 722, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/media/xxl/4TB_disk/work/Panoptic_segmentation/UPSNet-fixed/upsnet/upsnet_end2end_train.py", line 394, in <module>
    upsnet_train()
  File "/media/xxl/4TB_disk/work/Panoptic_segmentation/UPSNet-fixed/upsnet/upsnet_end2end_train.py", line 193, in upsnet_train
    output = train_model(data, label)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/xxl/4TB_disk/work/Panoptic_segmentation/UPSNet-fixed/upsnet/../upsnet/models/resnet_upsnet.py", line 139, in forward
    cls_label, bbox_target, bbox_inside_weight, bbox_outside_weight, mask_target)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/xxl/4TB_disk/work/Panoptic_segmentation/UPSNet-fixed/upsnet/../upsnet/models/rcnn.py", line 190, in forward
    cls_loss = self.cls_loss(cls_score, cls_label)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 862, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/nn/functional.py", line 1550, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/xxl/anaconda3/envs/py36_th04/lib/python3.6/site-packages/torch/nn/functional.py", line 1405, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (511) to match target batch_size (512).

Could you please help me solve the problems.

**Comment by YuwenXiong** [comment]
This error means you encounter training failure (usually because lr is too large), please note that upsnet_resnet50_coco.yaml is for 16 GPUs w/ Horovod, if you use that config w/o Horovod then you will only use 1 GPU and lr will be too large (however due to the warmup you may not encounter that issue at the beginning). If that is the case, please use upsnet_resnet50_coco_4gpu.yaml instead.

**Comment by Xiaolongbetter** [comment]
Thanks for your patience. The truth seems to be true. When I only use 1 GPU with upsnet_resnet50_coco.yaml, this error will appear around batch[300]. When I use 2 GPUs with upsnet_resnet50_coco_4gpu.yaml, this error will appear around batch[12000]. If I want to use two GPU training, can I guarantee the normal operation by reducing the lr in upsnet_resnet50_coco_4gpu.yaml, or I need to have at least 4 GPUs?

**Comment by YuwenXiong** [comment]
Then please double #iter and reduce lr by 2x

**Comment by Xiaolongbetter** [comment]
Thank you very much for your answer.

**Comment by discretecoder** [comment]
I am training on 4 channel inputs and getting the same error Expected input batch_size (503) to match target batch_size (512). with cityscapes

**Comment by discretecoder** [comment]
I am training on 4 channel inputs and I get a similar error while ROI aligning. in config, the pre-defined batch size is 512 and I get different ones per image. like 503, 497 etc and I get a similar error at 

"./upsnet/../upsnet/models/rcnn.py", line 191, in forward
    cls_loss = self.cls_loss(cls_score, cls_label)

 Expected input batch_size (503) to match target batch_size (512).

thanks :)

**Comment by discretecoder** [comment]
Thanks again for your great work. 
I have a similar question to this one. 
RCNN outputs a dictionary with cls_scores, bbox_pred and fc_feat. 
the dimension of these outputs is expected to be (512, _ ) from config.train.batch_rois=512 but I get different ones and a value error Expected input batch_size (511) to match target batch_size (512).

how do i fix this issue
