### ISSUE TITLE
Extension horovod.torch has not been built. 

### ISSUE THREAD

**Issue by reedwiththoughts** [uber-research/UPSNet#30]
Hello, After I run :
python upsnet/upsnet_end2end_train.py --cfg upsnet/experiments/upsnet_resnet50_coco.yaml

I encountered that: 
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

How should I do? Thanks for answering.

Traceback (most recent call last):
  File "/home/anaconda3/envs/pytorch1.0_python3.5/lib/python3.5/site-packages/horovod/torch/__init__.py", line 24, in <module>
    __file__, 'mpi_lib_v2')
  File "/home/anaconda3/envs/pytorch1.0_python3.5/lib/python3.5/site-packages/horovod/common/__init__.py", line 48, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.torch has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "upsnet/upsnet_end2end_train.py", line 44, in <module>
    import horovod.torch as hvd
  File "/home/anaconda3/envs/pytorch1.0_python3.5/lib/python3.5/site-packages/horovod/torch/__init__.py", line 27, in <module>
    __file__, 'mpi_lib', '_mpi_lib')
  File "/home/anaconda3/envs/pytorch1.0_python3.5/lib/python3.5/site-packages/horovod/common/__init__.py", line 48, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))

**Comment by YuwenXiong** [comment]
If you don't know how to run horovod properly, please use the 4gpu config file. And you can ask horovod-related issue at here: https://github.com/horovod/horovod

**Comment by reedwiththoughts** [comment]
OK, Thank you, YuwenXiong.

**Comment by lushishuai** [comment]
> If you don't know how to run horovod properly, please use the 4gpu config file. And you can ask horovod-related issue at here: https://github.com/horovod/horovod

hello，have you help him solve this problem?

**Comment by chauncygu** [comment]
my algorithm also has the problem:

ImportError: Extension horovod.torch has not been built:If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.

could any suggestions for solving this problem?
