### ISSUE TITLE
A error about logging

### ISSUE THREAD

**Issue by gh2517956473** [uber-research/UPSNet#43]
upsnet/../upsnet/config/config.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
Traceback (most recent call last):
  File "upsnet/upsnet_end2end_train.py", line 52, in <module>
    logger, final_output_path = create_logger(config.output_path, args.cfg, config.dataset.image_set)
  File "upsnet/../lib/utils/logging.py", line 38, in create_logger
    logging.basicConfig(filename=os.path.join(final_output_path, log_file), format=head)
AttributeError: 'module' object has no attribute 'basicConfig'

Process finished with exit code 0

**Comment by gh2517956473** [comment]
When I run python upsnet/upsnet_end2end_train.py --cfg upsnet/experiments/$EXP.yaml，this problem has arisen. My Python version is 3.6. Can you help debug？
Thank you very much！
