### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'log_dir'

### ISSUE THREAD

**Issue by reedwiththoughts** [uber-research/UPSNet#62]
Hello, after I run 

python upsnet/upsnet_end2end_train.py --cfg upsnet/experiments/upsnet_resnet50_coco_4gpu.yaml

I got 

upsnet/../upsnet/config/config.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
Traceback (most recent call last):
  File "upsnet/upsnet_end2end_train.py", line 56, in <module>
    time.strftime('%Y-%m-%d-%H-%M')))
  File "/home/wys/anaconda3/envs/pytorch0.4_python3.6/lib/python3.6/site-packages/tensorboardX/writer.py", line 254, in __init__
    self._get_file_writer()
  File "/home/wys/anaconda3/envs/pytorch0.4_python3.6/lib/python3.6/site-packages/tensorboardX/writer.py", line 310, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.logdir, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log_dir'

Could you tell me how to solve this problem? Thank you.

**Comment by reedwiththoughts** [comment]
When I delete  "logdir=" in line 56 of File "upsnet/upsnet_end2end_train.py", it disappears.

**Comment by Jacob-Jiah** [comment]
you can just try tensorboardX==1.6

**Comment by liand23** [comment]
I think 'log_dir' is used in the old versions of tensorboardX. Switching that with 'logdir' works for me.
