### ISSUE TITLE
Value error when evaluating on smaller set

### ISSUE THREAD

**Issue by gaussiangit** [uber-research/UPSNet#70]
I have smaller test image set, when I try to evaluate on smaller set. I have some nan values and it throws value error under unified section.

Following log: 

2019-07-06 20:50:18,300 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,300 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,300 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,301 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,301 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,301 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,301 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,301 | base_dataset.py | line 715: 1.000
2019-07-06 20:50:18,301 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,301 | base_dataset.py | line 715: 1.000
2019-07-06 20:50:18,301 | base_dataset.py | line 715: 1.000
2019-07-06 20:50:18,301 | base_dataset.py | line 715: 0.500
2019-07-06 20:50:18,301 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,301 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,302 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,302 | base_dataset.py | line 715: 1.000
2019-07-06 20:50:18,302 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,302 | base_dataset.py | line 715: nan
2019-07-06 20:50:18,302 | base_dataset.py | line 717: 0.627
2019-07-06 20:50:18,302 | base_dataset.py | line 719: ~~~~ Summary metrics ~~~~
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.396
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.627
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.418
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.268
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.258
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.612
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.289
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.465
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.471
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.330
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.295
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.674
2019-07-06 20:50:18,306 | upsnet_end2end_test.py | line 311: unified pano result:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "upsnet/../upsnet/dataset/base_dataset.py", line 546, in _pq_compute_single_core
    pan_gt_pred = pan_gt.astype(np.uint64) * OFFSET + pan_pred.astype(np.uint64)
ValueError: operands could not be broadcast together with shapes (426,640) (480,640) 
"""

**Comment by gaussiangit** [comment]
So my initial thought is that for the smaller set (smaller val2017) that I am evaluating, I should have panoptic gt as well if I am using evaluation script which computes PQ. Is there a quick way in your codebase to generate panoptic results on given test image without computing PQ ?
