### ISSUE TITLE
Undefined symbol Error 

### ISSUE THREAD

**Issue by benkmoore** [uber-research/UPSNet#71]
Hi

I'm trying to test the model and then use it for inference. I'm recieveing this error. I've tried mutliple version fo python with no success - pytohn 2.7, 3.5, 3.6 and 3.7

Ubuntu 16.04
Python 3.6
Cuda 10.1

`python3.6 upsnet/upsnet_end2end_test.py --cfg upsnet/experiments/upsnet_resnet101_cityscapes_w_coco_16gpu.yaml --weight_path ./model/upsnet_resnet_101_cityscapes_w_coco_3000.pth
3.6.9 (default, Jul  3 2019, 15:36:16) 
[GCC 5.4.0 20160609]
Traceback (most recent call last):
  File "upsnet/upsnet_end2end_test.py", line 44, in <module>
    from upsnet.dataset import *
  File "upsnet/../upsnet/dataset/__init__.py", line 1, in <module>
    from .cityscapes import Cityscapes
  File "upsnet/../upsnet/dataset/cityscapes.py", line 32, in <module>
    from upsnet.dataset.json_dataset import JsonDataset, extend_with_flipped_entries, filter_for_training, add_bbox_regression_targets
  File "upsnet/../upsnet/dataset/json_dataset.py", line 53, in <module>
    import upsnet.bbox.bbox_transform as box_utils
  File "upsnet/../upsnet/bbox/bbox_transform.py", line 15, in <module>
    from .bbox import bbox_overlaps as bbox_overlaps_cython
ImportError: upsnet/../upsnet/bbox/bbox.so: undefined symbol: _Py_ZeroStruct
`

Any help would be great, thanks!

**Comment by gaussiangit** [comment]
Try by downgrading Cuda to 9.1

**Comment by YuwenXiong** [comment]
Please try to rebuild all cython modules manually and make sure the python version matches the version you wish to run inference (i.e., use `python3.6 setup.py build_ext --inplace`)

**Comment by charlotte12l** [comment]
@YuwenXiong  I encounter a similar error, and rebuild all cython modules automatically or manually not working
`Traceback (most recent call last):
  File "upsnet/upsnet_end2end_test.py", line 44, in <module>
    from upsnet.models import *
  File "upsnet/../upsnet/models/__init__.py", line 1, in <module>
    from .resnet_upsnet import resnet_50_upsnet, resnet_101_upsnet
  File "upsnet/../upsnet/models/resnet_upsnet.py", line 22, in <module>
    from upsnet.models.resnet import get_params, resnet_rcnn, ResNetBackbone
  File "upsnet/../upsnet/models/resnet.py", line 21, in <module>
    from upsnet.operators.modules.deform_conv import DeformConv
  File "upsnet/../upsnet/operators/modules/deform_conv.py", line 22, in <module>
    from upsnet.operators.functions.deform_conv import DeformConvFunction
  File "upsnet/../upsnet/operators/functions/deform_conv.py", line 21, in <module>
    from .._ext.deform_conv import deform_conv_cuda
ImportError: upsnet/../upsnet/operators/_ext/deform_conv/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_32E
`
My build detail:
`
$ bash init.sh
Requirement already satisfied: pyyaml in /n/home05/xingyu/.conda/envs/ups/lib/python3.6/site-packages (5.1.1)
Requirement already satisfied: pycocotools in /n/home05/xingyu/.conda/envs/ups/lib/python3.6/site-packages (2.0.0)
fatal: destination path 'lib/dataset_devkit/panopticapi' already exists and is not an empty directory.
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
running build_ext
skipping 'anchors.c' Cython extension (up-to-date)
running build_ext
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)
running build_ext
copying build/lib.linux-x86_64-3.6/deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so -> 
running build_ext
copying build/lib.linux-x86_64-3.6/roi_align_cuda.cpython-36m-x86_64-linux-gnu.so -> 
`
