### ISSUE TITLE
DataParallel - AssertionError: Invalid device id

### ISSUE THREAD

**Issue by rasya-ramesh** [uber-research/UPSNet#91]
Traceback (most recent call last):
  File "upsnet/upsnet_end2end_train.py", line 407, in <module>
    upsnet_train()
  File "upsnet/upsnet_end2end_train.py", line 176, in upsnet_train
    train_model = DataParallel(train_model,  device_ids=[int(_) for _ in config.gpus.split(',')]).to(gpus[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 133, in __init__
    _check_balance(self.device_ids)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 19, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 19, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 318, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id

The above error pops up when running upsnet_end2end_train.py. I am at a loss as to why this error is occurring.

**Comment by rasya-ramesh** [comment]
I wanted to add that I am using Google Colab to run this code.

**Comment by IAMShashankk** [comment]
@rasya-ramesh were you able to solve it?
